version: 2.1

jobs:
  cypress:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Run Cypress tests :mag_right:"
      - run: cd client
      - run: npm install
      - run: npm run cy:test

workflows:
  cypress-workflow:
    jobs:
      - cypress
