version: 2.1
orbs: 
  cypress: cypress-io/cypress@1.29.0
workflows:
  build:
    jobs:
      - cypress/run:
          install-command: cd client && npm ci
          working_directory: client
