version: 2.1
orbs: 
  cypress: cypress-io/cypress@1.29.0
workflows:
  build:
    jobs:
      - cypress/run:
          install-command: npm i 
          working_directory: client
          start: npm start
          wait-on: 'http://localhost:3000'
