version: 2.1

jobs:
  cypress:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Run Cypress tests"
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run cy:test

workflows:
  say-hello-workflow:
    jobs:
      - cypress
