version: 2.1

jobs:
  cypress:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: echo "Run Cypress tests :mag_right:"
      - run: node --version
      - run: cd $(pwd)/client
      - run: ls
      # - run: npm install
      # - run: npm run cy:test

workflows:
  cypress-workflow:
    jobs:
      - cypress
