version: 2.1
orbs: 
  cypress: cypress-io/cypress@1.29.0
workflows:
  build:
    jobs:
      - cypress/install:
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "client/package.json"
            }}
      - cypress/run:
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "client/package.json"
            }}
          working_directory: client
